version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint-django.sh
    env_file:
      - .env
    expose:
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    container_name: improved_app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: improved_db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    container_name: improved_pgadmin

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - /home/dev/myproject/react-app/build:/usr/share/nginx/html:ro
    depends_on:
      - app
    container_name: improved_nginx

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    container_name: improved_redis

  celery:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app 
    depends_on:
      - db
    command: ./entrypoint-celery.sh
    container_name: improved_celery

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
