version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint-django.sh
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - static_data:/var/www/static/
      - media_data:/var/www/media/

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_data:/var/www/static/
      - media_data:/var/www/media/
      - certbot_certs:/etc/letsencrypt/
      - certbot_www:/var/www/certbot/
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt/
      - certbot_www:/var/www/certbot/
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email moustafa.alhaiba.2003@gmail.com -d serinek.com -d www.serinek.com --agree-tos --no-eff-email

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app 
    depends_on:
      - db
    command: ./entrypoint-celery.sh
  
volumes:
  postgres_data:
  static_data:
  media_data:
  redis_data:
  certbot_certs:
  certbot_www: